import model.Etage;
import model.Hotel;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Hotel hotel = new Hotel("pouet");

        hotel.add(new Etage());

        for(Etage etage : hotel.getEtages()) {
            System.out.println(etage.toString());
        }
    }
}
